// TODO: Finish adding obj vars to facilitate SID / Class
// TODO: Add specific levels for evolutions
// TODO: Implement logic for discerning evolutions based on stats

const MagList = {
  mag: {
    id: {
      hunter: {
        bluefull: "Mag",
        greenil: "Mag",
        oran: "Mag",
        pinkal: "Mag",
        purplenum: "Mag",
        redria: "Mag",
        skyly: "Mag",
        viridia: "Mag",
        yellowboze: "Mag",
        whitill: "Mag"
      },

      ranger: {
        bluefull: "Mag",
        greenil: "Mag",
        oran: "Mag",
        pinkal: "Mag",
        purplenum: "Mag",
        redria: "Mag",
        skyly: "Mag",
        viridia: "Mag",
        yellowboze: "Mag",
        whitill: "Mag"
      },

      force: {
        bluefull: "Mag",
        greenil: "Mag",
        oran: "Mag",
        pinkal: "Mag",
        purplenum: "Mag",
        redria: "Mag",
        skyly: "Mag",
        viridia: "Mag",
        yellowboze: "Mag",
        whitill: "Mag"
      }
    },

    monomate: {
      sync: 3,
      iq: 3,
      def: 5,
      pow: 40,
      dex: 5,
      mind: 0,
    },
    dimate: {
      sync: 3,
      iq: 3,
      def: 10,
      pow: 45,
      dex: 5,
      mind: 0,
    },
    trimate: {
      sync: 4,
      iq: 4,
      def: 15,
      pow: 50,
      dex: 10,
      mind: 0,
    },
    monofluid: {
      sync: 3,
      iq: 3,
      def: 5,
      pow: 0,
      dex: 5,
      mind: 40,
    },
    difluid: {
      sync: 3,
      iq: 3,
      def: 10,
      pow: 0,
      dex: 5,
      mind: 45,
    },
    trifluid: {
      sync: 4,
      iq: 4,
      def: 15,
      pow: 0,
      dex: 10,
      mind: 50,
    },
    antidote: {
      sync: 3,
      iq: 3,
      def: 5,
      pow: 10,
      dex: 40,
      mind: 0,
    },
    antiparalysis: {
      sync: 3,
      iq: 3,
      def: 5,
      pow: 0,
      dex: 44,
      mind: 10,
    },
    sol: {
      sync: 4,
      iq: 1,
      def: 15,
      pow: 30,
      dex: 15,
      mind: 25,
    },
    moon: {
      sync: 4,
      iq: 1,
      def: 15,
      pow: 25,
      dex: 15,
      mind: 30,
    },
    star: {
      sync: 6,
      iq: 5,
      def: 25,
      pow: 25,
      dex: 25,
      mind: 25,
    },
  },

  evo1: {
    id: {
      hunter: {
        bluefull: "Varuna",
        greenil: "Varuna",
        oran: "Varuna",
        pinkal: "Varuna",
        purplenum: "Varuna",
        redria: "Varuna",
        skyly: "Varuna",
        viridia: "Varuna",
        yellowboze: "Varuna",
        whitill: "Varuna"
      },

      ranger: {
        bluefull: "Kalki",
        greenil: "Kalki",
        oran: "Kalki",
        pinkal: "Kalki",
        purplenum: "Kalki",
        redria: "Kalki",
        skyly: "Kalki",
        viridia: "Kalki",
        yellowboze: "Kalki",
        whitill: "Kalki"
      },

      force: {
        bluefull: "Vritra",
        greenil: "Vritra",
        oran: "Vritra",
        pinkal: "Vritra",
        purplenum: "Vritra",
        redria: "Vritra",
        skyly: "Vritra",
        viridia: "Vritra",
        yellowboze: "Vritra",
        whitill: "Vritra"
      }
    },
    level: 10,
    monomate: {
      sync: 0,
      iq: 0,
      def: 5,
      pow: 10,
      dex: 0,
      mind: -1,
    },
    dimate: {
      sync: 3,
      iq: 3,
      def: 10,
      pow: 45,
      dex: 5,
      mind: 0,
    },
    trimate: {
      sync: 4,
      iq: 4,
      def: 15,
      pow: 50,
      dex: 10,
      mind: 0,
    },
    monofluid: {
      sync: 3,
      iq: 3,
      def: 5,
      pow: 0,
      dex: 5,
      mind: 40,
    },
    difluid: {
      sync: 3,
      iq: 3,
      def: 10,
      pow: 0,
      dex: 5,
      mind: 45,
    },
    trifluid: {
      sync: 4,
      iq: 4,
      def: 15,
      pow: 0,
      dex: 10,
      mind: 50,
    },
    antidote: {
      sync: 3,
      iq: 3,
      def: 5,
      pow: 10,
      dex: 40,
      mind: 0,
    },
    antiparalysis: {
      sync: 3,
      iq: 3,
      def: 5,
      pow: 0,
      dex: 44,
      mind: 10,
    },
    sol: {
      sync: 4,
      iq: 1,
      def: 15,
      pow: 30,
      dex: 15,
      mind: 25,
    },
    moon: {
      sync: 4,
      iq: 1,
      def: 15,
      pow: 25,
      dex: 15,
      mind: 30,
    },
    star: {
      sync: 6,
      iq: 5,
      def: 25,
      pow: 25,
      dex: 25,
      mind: 25,
    },
  },

  evo2_0: {
    names: ["Ashvinau", "Sumba", "Namuci", "Marutah", "Rudra"],
    level: 35,
    monomate: {
      sync: 0,
      iq: -1,
      def: 1,
      pow: 9,
      dex: 0,
      mind: -5,
    },
    dimate: {
      sync: 3,
      iq: 0,
      def: 1,
      pow: 13,
      dex: 0,
      mind: -10,
    },
    trimate: {
      sync: 4,
      iq: 1,
      def: 8,
      pow: 16,
      dex: 2,
      mind: -15,
    },
    monofluid: {
      sync: 0,
      iq: -1,
      def: 0,
      pow: -5,
      dex: 0,
      mind: 9,
    },
    difluid: {
      sync: 3,
      iq: 0,
      def: 4,
      pow: -10,
      dex: 0,
      mind: 13,
    },
    trifluid: {
      sync: 3,
      iq: 2,
      def: 6,
      pow: -15,
      dex: 5,
      mind: 17,
    },
    antidote: {
      sync: -1,
      iq: 1,
      def: -5,
      pow: 4,
      dex: 12,
      mind: -5,
    },
    antiparalysis: {
      sync: 0,
      iq: 0,
      def: -5,
      pow: -6,
      dex: 11,
      mind: 4,
    },
    sol: {
      sync: 4,
      iq: -2,
      def: 0,
      pow: 11,
      dex: 3,
      mind: -5,
    },
    moon: {
      sync: -1,
      iq: 1,
      def: 4,
      pow: -5,
      dex: 0,
      mind: 11,
    },
    star: {
      sync: 4,
      iq: 2,
      def: 7,
      pow: 8,
      dex: 6,
      mind: 9,
    },
  },

};

export default MagList;
